### ISSUE TITLE
Router doesn't handle 404

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#112]
The router needs to return a status of 404 when a route is not defined.

We also need a default 404 page that can be customized by the developer

**Comment by xepozz** [comment]
We can create .htaccess and add default page for 404 error.

**Comment by RogerCreasy** [comment]
We should handle it with PHP so that it works for other servers. i.e. Nginx

**Comment by geekfred** [comment]
Sure, where's does this should happen? And how would you like to define the 404? like we could just throw a 404 template and work that file.
