### ISSUE TITLE
middleware "before" not working

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#124]
All middleware is applied after the route or controller output. The middleware system needs to be improved in general. It is a WIP. So, if anyone wants to suggest/make improvements, please do.

**Comment by Cleanse** [comment]
It looks as if you were working off an example, could you share the source? I might be able to get namespaces working.

**Comment by RogerCreasy** [comment]
No example...I just hacked at it up to this point.
What do you mean regarding namespaces? Everything works for me, except middleware is only applied after the route or controller response changes. We may need another issue for your situation and namespaces.

**Comment by Cleanse** [comment]
I meant to say middleware, sorry.

**Comment by RogerCreasy** [comment]
@Cleanse NP. I am hacking at it some more. Have not made much progress.

**Comment by RogerCreasy** [comment]
completed with PR #130
