### ISSUE TITLE
Need an auth system

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#13]
there needs to be a built auth system for access to the backend.

- multiple levels of user rights

1. admin - include user management, page creation
2. editor - content editing and creation
3. other?

**Comment by RogerCreasy** [comment]
Review the Zend Auth system

**Comment by MisterBrownRSA** [comment]
@RogerCreasy I can look at this if you'd like.

Basically just log in and keep the auth session, correct ?

**Comment by RogerCreasy** [comment]
@MisterBrownRSA Great!
Yes, log in and keep the session. We also need to give the app access to who the logged-in user is. We need access levels and will need to have the user level for middleware filtering.
i.e. Admins who can do anything, Editors who can change content.
The SQLite DB should be set up. You can add users through the SQLite CLI for now.

I am going to add some related issues - password encryption, add user form. But, those can be worked on separately from the backend auth bits. For now, this issue can just handle checking against the DB and populating the session.
Thoughts? I am open to a different approach.

**Comment by RogerCreasy** [comment]
@MisterBrownRSA 
@peppeocchi added a clash with hash functionality. The functions are static.
The class is at \Lib\Framework\ and is named Hash.php

**Comment by RogerCreasy** [comment]
The Session class has been added. I am working on getting it populated via middleware.
@MisterBrownRSA tagging you in case you are still looking at this.

**Comment by RogerCreasy** [comment]
handled via PR #164
