### ISSUE TITLE
Add tests for routing

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#22]

**Comment by RogerCreasy** [comment]
I really need help with testing. I welcome PRs for tests.

**Comment by andradedev** [comment]
@RogerCreasy  i can work on that

**Comment by RogerCreasy** [comment]
@andradedev Great! I am not very good with tests. I may have questions for you. Keep in mind that if you are doing this for Hacktoberfest, PRs have to be made between October 1 and 31 in order to count.

**Comment by dangenendt** [comment]
What routing do you exactly mean? The Route-class in lib/Framework? 
If yes, unit testing this class would need some small refactorings.

**Comment by RogerCreasy** [comment]
@dangenendt yes. But, @andradedev is working on this one. Perhaps we can discuss the steps/changes needed here, and we can all work on it?

**Comment by dangenendt** [comment]
@RogerCreasy Yes, i saw that @andradedev is working on that. I just where interested in that one :)
thanks for the info

**Comment by RogerCreasy** [comment]
@dangenendt we need other tests; I am not good with testing....If you are, would you be willing to help with others where you see a need? Feel free to open issues. If you do, and you want me to tag them as Hacktoberfest, let me know.

**Comment by dangenendt** [comment]
I'm pretty new to ChassisPHP. What important functionality should be tested except the routing? What would you recommend?

**Comment by RogerCreasy** [comment]
I just took a quick look through the project, and with my limited knowledge of testing, I don't see much.
I am working on PSR-7 implementation, which will add a need for testing responses and requests on the container. Middleware, logging, and authentication testing will come soon too. 
Sorry. There will be more soon,
THanks so much for your willingness to help!

**Comment by dangenendt** [comment]
@RogerCreasy
No problem. 
If the code is ready, feel free to mention me. 
I can take a look on it then.
