### ISSUE TITLE
Add a development branch to improve workflow

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#309]
As we progress, this will make tagged releases easier.

**Comment by bolint** [comment]
Would not it be better for the `master` as a development branch and a new `production` branch for the live code?

**Comment by RogerCreasy** [comment]
Changed default branch to 0.1.x
The plan is to use semantic versioning and name branches accordingly. This change should give users of the package the ability to use the version they wish, and update as they are able.
