### ISSUE TITLE
Add How-To instructions

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#31]

**Comment by RogerCreasy** [comment]
This could be an easy PR for hactoberfest. I welcome even a simple start to how-to.

**Comment by Divya063** [comment]
@RogerCreasy Can I work on this?

**Comment by RogerCreasy** [comment]
@Divya063 yes! If you are doing this for Hacktoberfest credit, keep in mind that PRs don't count until October 1. It will take a bit of a code dive on your part. Let me know of questions. Also, the code base is very incomplete. So, there will likely be missing bits in your How-to, and I understand that.

**Comment by MisterBrownRSA** [comment]
Is there anything else required here?

**Comment by RogerCreasy** [comment]
I don't think so at this point in the development.
However, when we are closer to production-ready, perhaps?

**Comment by RogerCreasy** [comment]
Closing this until next year.
Thanks to all who contributed for Hactoberfest. I hope you were successful in completing all of your PRs!
PLEASE continue to contribute. **You** are what pushed ChassisPHP to become a real project!
