### ISSUE TITLE
Config files can overwrite each other

### ISSUE THREAD

**Issue by dominikb** [RogerCreasy/ChassisPHP#327]
# Flattening of config files
The config manager `\Lib\Framework\Config` takes in all files placed in the `Config/` Folder and parses them. It takes all first level keys of config files and places them into a global config array.  

Currently, there is no further ability to identify in which config file a key was set, as the Manager flattens the input.

This behavior also requires that each key inside a configuration file must be another array, which seems redundant.

## Example
app.php
````php
return [
   'name' => 'Some Name',
   'facts' => [
      'bears' => 'Bears are mammals.',
   ]
];
````
This would throw an error because it tries to resolve `name` as an array

_false_facts.php
````php
return [
  'facts' => [
    'bears' => 'Bears are birds.',
  ],
];
````
This file would get loaded first because of the **_** prefix and would not allow `app.php` to correctly set bear facts.

# Proposal
Refactor the Config Manager to resolve file names into first level array keys and handle nesting at different levels.

Resulting config should be like
````php
$config = [
  'app' => [
    'name' => 'Some Name',
    'facts' => [
      'bears' => 'Bears are marmals.',
     ]
  ],
  '_false_facts' => [
    'facts' => [
       'bears' => 'Bears are birds.',
    ],
  ],
];
````

**Comment by RogerCreasy** [comment]
Handled with PR #328
