### ISSUE TITLE
add logging system

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#54]

**Comment by MisterBrownRSA** [comment]
I'll work on this

**Comment by MisterBrownRSA** [comment]
I can't git clone this... will composer install, but might want to have a look at your publickey

**Comment by RogerCreasy** [comment]
@MisterBrownRSA thanks! Which logger package are you considering? Or, are you going to write from scratch? I was considering Monolog. I am open to others.

**Comment by MisterBrownRSA** [comment]
@RogerCreasy while doing composer install I saw a psr/log logger interface. Was thinking about simply using what you've already got instead of requiring a new dependency. Will let you know.

**Comment by RogerCreasy** [comment]
@MisterBrownRSA Sorry about that. The .env could be the problem. I'll get an example added soon.
You may need to set up an sqlite db as well.

**Comment by RogerCreasy** [comment]
@MisterBrownRSA .env.example has been added. Let me know if this fixes your issue.

This example will evolve as the framework grows.

**Comment by MisterBrownRSA** [comment]
for Hacktoberfest, can we only contribute to issues that have been tagged as such, or can a person contribute to anything with regards to the project and still count ?

**Comment by RogerCreasy** [comment]
I think anything....but, if you want me to tag something on this project, just to be safe, I am happy to do so.
Just let me know.

**Comment by RogerCreasy** [comment]
CLosing issue. Let me know of issues I need to tag with Hactoberfest using the Hactoberfest issue conversation.
