### ISSUE TITLE
Change logging to log to the Storage directory

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#77]
perhaps a /logs sub-directory within storage. I am working on sessions now, and hope to create the Storage directory soon. I'll also add Storage to .gitignore

Tagging @MisterBrownRSA

**Comment by RogerCreasy** [comment]
I added the storage directory

**Comment by ghosh** [comment]
Hey, I can pick this up. Will the change be made in `lib/Framework/Container.php`?

**Comment by RogerCreasy** [comment]
I think @MisterBrownRSA  is working on it. @MisterBrownRSA  ?

**Comment by MisterBrownRSA** [comment]
Hi,  yes.  I will be working on this feature. Thank you

**Comment by ghosh** [comment]
ok, thanks for notifying.

**Comment by RogerCreasy** [comment]
@ghosh Thanks for your willingness to help. WOuld you like to work on another issue? Or one that you find?

**Comment by RogerCreasy** [comment]
completed with PR #81
