### ISSUE TITLE
Move Twig cache into the storage directory

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#86]
This is set in the initiation in the container; use the dirname(__FILE__, 3) structure for consistency.
As part of this change, we need to make sure the current cache location is not committed. The new location will also need .gitignore configuration.

**Comment by MisterBrownRSA** [comment]
I'll look into this. I'm sorry, I thought this was already done.

**Comment by RogerCreasy** [comment]
@MisterBrownRSA No problem. I figured it was another easy PR for Hacktoberfest. The change appears to be relatively straightforward. Let me know if you run into any problems.

Currently it saves the cache to lib/Framework/storage/sessions

**Comment by MisterBrownRSA** [comment]
#87

**Comment by RogerCreasy** [comment]
There are some tests in the repo; they do use phpunit.

I really was just hacking at it though. tests are a weakness for me. There is also an issue for testing routes, but @andradedev said they would work on it. Feel free to open issues on other tests, or anything you see. I would like to add badges for test coverage and try to get good coverage. But, like I said, I still have much to learn with testing.

**Comment by andradedev** [comment]
@RogerCreasy yes, actually i working fixing the issues, and adding to routes, after that i will add to other stuff too

**Comment by RogerCreasy** [comment]
@andradedev Cool! Thanks!

**Comment by RogerCreasy** [comment]
Resolved with PR #87
