### ISSUE TITLE
Add templating

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#9]
Looking into Twig - most likely choice

**Comment by MisterBrownRSA** [comment]
I'll be looking into this.

**Comment by RogerCreasy** [comment]
You've got it.
Thanks!

**Comment by MisterBrownRSA** [comment]
#83

**Comment by RogerCreasy** [comment]
completed with PR #83

**Comment by RogerCreasy** [comment]
@MisterBrownRSA I moved the views directory into a resources directory because I thought it might be good to be able to put css and javascript directories within resources as well. That way we can automatically compile multiple css or js files into single files and move (automatically) them into the public directory.
