### ISSUE TITLE
Need a way to clear template cache from the command line

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#90]
It looks like Twig does not have a native solution to this issue.

When developing a site, devs need a way to clear the template cache in order to check changes to template files.

**Comment by modelorona** [comment]
Hello Roger,

I've not much experience with Twig but I came across [this](https://twig.symfony.com/doc/2.x/api.html).

When creating the Twig environment, the `auto_reload` can be set to true in order for the templates to be re-compiled once the source code changes. However, I was not able to find where exactly in your code you set up the Twig environment variables.

Would this help if it was incorporated into the codebase?

**Comment by RogerCreasy** [comment]
Cool find! Thanks!
It looks like it would solve the real problem, and perhaps better than the way I defined it.

Twig is set up in the Container (lib/Framework/Container.php) I am new to Twig as well...but, perhaps it is set up in the Twig_Environment constructor? I can look in a bit, unless you want to take it on?

**Comment by RogerCreasy** [comment]
@modelorona Thanks for pointing this out. I researched a bit and found that this setting does, in fact, update the cache when you change a template file. Do you want to make a PR for the fix?
All it takes is adding 'auto_reload' => true, to the Twig_Environment settings array in the container.

**Comment by modelorona** [comment]
Sure! I can do that

**Comment by RogerCreasy** [comment]
Completed with PR #95
